### ISSUE TITLE
Error execute command

### ISSUE THREAD

**Issue by vinhnx** [angelolloqui/AGi18n#15]
I'm using zsh as my default shell. When I run either `agi18n` or `genxibstrings` command, it's always return error 

```bash
$ agi18n 
zsh: exec format error: agi18n

$ genxibstrings
zsh: exec format error: genxibstrings
```

Mac OS 10.10 dev preview 2, iTerm

Do you have idea how to fix this? Thanks!

**Comment by angelolloqui** [comment]
Closing due to very old issue. Please reopen with more info if you still have it
