### ISSUE TITLE
Cocoapods install running on device

### ISSUE THREAD

**Issue by oligriffiths** [angelolloqui/AGi18n#16]
Hi

The +(void)load; method does not get called when running on a device if the library is installed via cocoapods.

I believe the issues is the library is not included as a static library, see

http://stackoverflow.com/questions/6047903/voidload-message-not-sent-to-framework-class-in-device-runtime

Any ideas?

Oli

**Comment by angelolloqui** [comment]
Interesting... I have all my projects with Pods and I do not have the issue. Have you tried with the -`force_load `?

**Comment by oligriffiths** [comment]
No, how does force_load work?

**Comment by angelolloqui** [comment]
I am closing this issue as it quite old and I am using it in different projects with Pods with no issues. Please feel free to reopen if any new findings...
