### ISSUE TITLE
Swift file genstring

### ISSUE THREAD

**Issue by mihriminaz** [angelolloqui/AGi18n#21]
// Execute genstrings appending results
	puts "Executing `genstrings -a -o #{dir} **/*.{h,m,mm}`"	
	source_files = Dir["**/*.{h,m,mm}"]
 	`genstrings -a -littleEndian -o #{dir} "#{source_files.join('" "')}"`
 	
.swift should be included, otherwise genstrings don't include the localisation for swift files..

//Execute genstrings appending results
	puts "Executing `genstrings -a -o #{dir} **/*.{h,m,mm, swift}`"	
	source_files = Dir["**/*.{h,m,mm, .swift}"]
 	`genstrings -a -littleEndian -o #{dir} "#{source_files.join('" "')}"`

**Comment by angelolloqui** [comment]
Good catch! thanks, just added it
