### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by virulaine** [angelolloqui/AGi18n#22]
Ruby 2.0.0p481, XCode 6.3, OSX Yosemite 10.10.3
When I run "curl https://raw.github.com/angelolloqui/AGi18n/master/bin/install.sh | sh", empty transfer occurs. No messages in console. Nothing.
OK, downloaded manually 2 utils to /usr/local/bin/
Went to source code folder and executed "agi18n" - still nothing in console.

**Comment by angelolloqui** [comment]
What do you mean by nothing in console? the script does "echo" some messages so I do not see how can you get "nothing". It is hard to help with this feedback...

**Comment by virulaine** [comment]
Here is screenshot https://www.dropbox.com/s/n68pj869xkyarit/Screen%20Shot%202015-05-01%20at%2014.41.12.png?dl=0

**Comment by angelolloqui** [comment]
That is strange. Have you checked if the `genxibstrings` and `agi18n` are in the `/usr/local/bin/` directory?  Have you tried downloading the 2 script files manually?

**Comment by virulaine** [comment]
Yes, they are in my /usr/local/bin https://www.dropbox.com/s/ciiy3jsfsdtp0dz/Screen%20Shot%202015-05-03%20at%2018.20.05.png?dl=0 and I downloaded them manually.
If I run agi18n from console, it doesn't display any "echo" messages.

**Comment by virulaine** [comment]
Any chance to fix this? Or if this project not maintained anymore, please add note into readme.md

**Comment by angelolloqui** [comment]
Well... this project is mantained by people like you, so please feel free to do any change you need...

**Comment by azamouchi** [comment]
i've had the same issue, when i tried to use the curl command to download the .sh file i get an empty transfer. Instead i manually downloaded the two files from in the /bin directory in this repo, and copied them  to usr/loca/bin. This fixed the problem.
Note : if you are working with a workspace (in case you are using CocoaPods for example), make sure to run the commande(agi18n) inside your project root directory and not inside the workspace root directory, or no language will be detected .
