### ISSUE TITLE
awakeFromNibCustom never called

### ISSUE THREAD

**Issue by raspu** [angelolloqui/AGi18n#23]
I am not really sure when this started to happen, but suddenly even after `+load` make the swizzle exchange, `awakeFromNibCustom` never get's called, but the regular `awakeFromNib` does. 

I am using xcode 6.3.2 (6D2105) and iOS 8.3 SDK and I installed it using cocoapods (0.37.2).

**Comment by angelolloqui** [comment]
Do you have any other piece of code doing swizzling on the method? I have 6.3.2 and seems to be working fine...

**Comment by raspu** [comment]
Nop, I am using AFNetworking and BlocksKit, both of them do swizzling, but I have been using them from the start...

 This quite strange, I don't see any difference in configuration neither... Another developer changed some things recently, but nothing that would break AGi18n...

**Comment by angelolloqui** [comment]
Are you using Storyboards or plain XIB files? I would like to try to reproduce in an empty project...

**Comment by raspu** [comment]
Xib files only. I am trying to fix it, if I find the problem I'll let you know.

**Comment by raspu** [comment]
I was able to isolate the issue to one commit, I think the problem is a conflict with IQKeyboardManager pod.

**Comment by raspu** [comment]
Yes, if I remove IQKeyboardManager works perfectly. I will be closing this issue as it it's not directly related with the library, sorry.

**Comment by codeflayer** [comment]
I do it as you video, it never work for me ,make me crezy ,please help@angelolloqui
![f5220527-8d41-42d8-89f9-39989f71fce1](https://user-images.githubusercontent.com/8957164/30262890-58bc673a-9705-11e7-8aff-b5b1507a557f.png)
![f5220527-8d41-42d8-89f9-39989f71fce1](https://user-images.githubusercontent.com/8957164/30262905-6a8fd1fe-9705-11e7-938f-d659719311e0.png)

**Comment by codeflayer** [comment]
can you post your demo?I think it's will help a lot.
