### ISSUE TITLE
No explanation of what "AGi18n" means is given.

### ISSUE THREAD

**Issue by Jessy-** [angelolloqui/AGi18n#25]
I will not use a thing with a confusing name, because I will always have that confusion interrupting my flow, when using it. Please provide this at the beginning of the documentation, or just change the name to something that doesn't require an explanation.

**Comment by Jessy-** [comment]
Okay, after removing AG, it was easy to learn about i18n, which is in itself confusing. Please provide that information to the uninitiated.

I think the name is okay, until we have better namespace support, which would allow AngeloGarcia.i18N.

**Comment by angelolloqui** [comment]
Not sure what do you mean by confusing name, as i18n is a well known shortcut for Internazionalization (I + 18 chars + n) . Namespaces are always used in Obj-C libraries, and AG follows the standard convention of 2/3 letter prefix. Therefore closing this issue.

**Comment by Jessy-** [comment]
It wasn't well-known to me. I just saw a jumble of letters. I'm surely not the last person who will have this temporary issue, so I think it would be nice of you to at least provide a Wikipedia link, but it's your prerogative if you want to keep out the riffraff via obfuscation. ;-)
