### ISSUE TITLE
Xcode 6.4

### ISSUE THREAD

**Issue by Ged2323** [angelolloqui/AGi18n#27]
Hi Iwas trying this with Xcode 6.4 and it won't alter the names of elements within storyboards.
Or am I doing something wrong?

**Comment by angelolloqui** [comment]
I can not see any reason for Storyboards to not localize properly. The library is based on the call to `awakeFromNib`, so as long as that is called then it should work properly (and that is indeed the case). Can you check if you have imported the lib files properly?

**Comment by Ged2323** [comment]
Hi Angel,

I’ve managed to get it to work with a swift project though it’s a bit of a procedure.
I’ve got it working with the main storyboard but not the launchscreen.xib


Yours Sincerely
Gerard Grundy

**Comment by angelolloqui** [comment]
That is a good point. The launch screen procedure is a special one, so I think you will need to keep that one with the standard localization.
On the other hand, can you elaborate on the problems for Swift projects? I am using Pods and I do not see much of a problem.

Thanks for the feedback.

**Comment by Ged2323** [comment]
Hi,
When I try to import and run the agi18n in the path of the project it doesn't work for me but it I drag the file into terminal from the bin file in my downloads its works no worries. 
Am I doing that right?  
How do you run the pod? 
I've tried running the pod file but I couldn't get it to run. 
Regards Gerard Grundy
