### ISSUE TITLE
I do it as you video, it never work for me ,make me crezy ,please help@angelolloqui

### ISSUE THREAD

**Issue by codeflayer** [angelolloqui/AGi18n#34]
can you post your demo?I think it's will help a lot.
![f5220527-8d41-42d8-89f9-39989f71fce1](https://user-images.githubusercontent.com/8957164/30263282-e29f4ad4-9706-11e7-879d-1a34d7e0c62c.png)

**Comment by angelolloqui** [comment]
Can you explain what it doesn't work? Is it extracting the labels from the con files with the tool? Or is it the translation? 
You are showing a screenshot of an empty Localizable file, but can you post the command you are running with the error?

**Comment by angelolloqui** [comment]
BTW, I see you have the command line scripts as part of your project... not sure why... please provide the steps you are following if you are not following the readme file

**Comment by codeflayer** [comment]
I'm not install command line utilities, I just copy and paste the genxibstrings and agi18n files in program ,then  added Chinese and English, double click agi18n, nothing happened.  genxibstrings seems not work . how I use genxibstrings?

**Comment by codeflayer** [comment]
console  log this 
![default](https://user-images.githubusercontent.com/8957164/30271477-0a2fa276-9723-11e7-9bd1-cdf11eac986d.png)

**Comment by angelolloqui** [comment]
If it does not detect any of the strings is probably because you are running it out of your project folder. The tool will look into your folder looking for xib files.

**Comment by codeflayer** [comment]
I move it into another folder ,it works !!!!! then I translate Chinese into English, I set iPhone   Language as English,nothing happened, it appears still Chinese. how can I do? My friend does't work ,neither. here it is.
![test](https://user-images.githubusercontent.com/8957164/30303942-740ba7ce-979d-11e7-92b3-9fa4f5c047fb.png)

**Comment by codeflayer** [comment]
it seems like this caused  by without .h,I put it back, it succeed. How did this happend ???
![test](https://user-images.githubusercontent.com/8957164/30308115-94902d22-97b5-11e7-905d-792a0877dd4f.png)

**Comment by angelolloqui** [comment]
It is explained in the readme. The project has 2 parts. The tool is to help you extracting the strings, but it does not translate. The lib (under the lib folder) is to make the translations. You can use them separately or together, as you prefer.

To use the lib you have to include the files into your project, as explained in the readme

**Comment by angelolloqui** [comment]
Another thing I see in your screenshot is that the localizable file is not imported properly because it appears under 2 folders but it should appear as 1 file with 2 options inside. I think you imported it manually instead of just using the standard Localizable file created by Xcode when you add multiple languages to the project, but this is an issue on your side and not the tool.

Closing the issue for now...

**Comment by codeflayer** [comment]
Maybe  I not  make  it clear, what I'm try to say is  ".m" file  may  add   a line  "#import <UIKit/UIKit.h>", or  Undefined symbol in Xcode.  
![232](https://user-images.githubusercontent.com/8957164/30312324-8b0c3078-97cb-11e7-9349-9bf34756590c.png)

**Comment by angelolloqui** [comment]
I have pushed a new version (0.0.4) with the fix. Thanks
