### ISSUE TITLE
Error walking through third-party library issues

### ISSUE THREAD

**Issue by newIOS1** [angelolloqui/AGi18n#36]
Hi, agi18n has some problems. Extract. String failed in m. Errors such as attachments. I've found it traversing some of the third-party libraries, asking for your help to make it no longer traverse
![2017-09-12 7 49 04](https://user-images.githubusercontent.com/7839555/30325574-e1420586-97f7-11e7-9cce-c0088c558463.png)

**Comment by angelolloqui** [comment]
I do not see erros there. The `genstrings` tool from Apple is warning that some files have wrong encoding but it is apparently working OK. Traversing is required to extract all possible localization strings contained in any of your project files, but normally the third party libs are stored in a different folder (either `pods` if you use cocoapods, `carthage` if using Carthage or something like `vendor` if you do it manually)

What exactly does it fail? Remember that running the tool is not needed to do translations, only the `lib` part is. The tools are only helpers to extract the texts
