### ISSUE TITLE
xcode9  WARNING: Unhandled destination metrics: (null)

### ISSUE THREAD

**Issue by newIOS1** [angelolloqui/AGi18n#38]
Hi, xcode 9 executes the agi18n command, which is followed by a warning： WARNING: Unhandled destination metrics: (null)
![2017-09-21 4 25 41](https://user-images.githubusercontent.com/7839555/30686132-d4ce188c-9ee9-11e7-89d5-0e24c5aaf8be.png)

**Comment by leavesster** [comment]
My solution:
use `agi18n 2>/dev/null` instead of `agi18n`
It just a trick not a fix.
