### ISSUE TITLE
Agi18n seems not work in macOS High Sierra (10.13)

### ISSUE THREAD

**Issue by leavesster** [angelolloqui/AGi18n#39]
After update to High Sierra. 
I run agi18n script. it seems not work any more, just like I annotation `# agi18n` in shell script.

It seems High Sierra change some terminal command ?

Environment:
not work in Xcode 9 && High Sierra.
work in Xcode9 && Sierra.

**Comment by leavesster** [comment]
It just cann't load string from xib.

**Comment by angelolloqui** [comment]
Are you looking into it? or am I supposed to investigate it myself with this information?

**Comment by leavesster** [comment]
Sorry for not give enough information ... 

At first I thought the reason is 10.13 (all my colleagues have this issue). So I didn't give more information.

Today I try to reproduce this problem and create a demo for this issue.
However when I try reproduce it on my personal mbp which is also 10.13, it just print `ibtoold[4680:1342972] WARNING: Unhandled destination metrics: (null)` (when the project has xib.) 
But it works fine, the localizedString contain all strings.

I think I should figure it out myself……seems it just work in special situation.
When I solve this, I will comment the reason and close this issue.
Thanks for reply and forgive my poor English >_<.

**Comment by angelolloqui** [comment]
Great! thanks! closing for now but if you find something out we will reopen...

**Comment by leavesster** [comment]
I finally find the reason. 

It because my script has the this error.

```
/usr/local/bin/agi18n:21:in `match': incompatible encoding regexp match (UTF-16LE regexp with UTF-8 string) (Encoding::CompatibilityError)
	from /usr/local/bin/agi18n:21:in `block in remove_duplicates'
	from /usr/local/bin/agi18n:19:in `each'
	from /usr/local/bin/agi18n:19:in `remove_duplicates'
	from /usr/local/bin/agi18n:74:in `block in <main>'
	from /usr/local/bin/agi18n:60:in `each'
	from /usr/local/bin/agi18n:60:in `<main>'
```

When in macOS 10.13, after arise this error, `agi18n` don't generate `Localizable.strings` and stop work.
But in macOS 10.12, `agi18n` still generate `Localizable.strings` for each lproj.

So it seems agi18n not work. And the reason why it `It just cann't load string from xib.` is because my script use apple `genstrings` before use `agi18n` .

**Comment by leavesster** [comment]
The error hide in crazy warning `WARNING: Unhandled destination metrics: (null)` , so I always ignore the crazy log ……
after I use `my_script > log.txt 2>&1`. I find the error .strings files in log.txt.

My Solution: convert `.strings` files to UTF-8 after agi18n works. 
I convert `.strings` files to UTF-8 just because I use python script to translate.

I don't think others will have this problem. But It is quite weird between 10.13 and 10.12.

Thank you~
