### ISSUE TITLE
Custom tableName

### ISSUE THREAD

**Issue by stasivanov** [angelolloqui/AGi18n#40]
I have a problem now. I want to have multiple Strings files for translations.

The idea is to have a separate Strings file for each _ViewController_ or _XIB_.

To make this works, I would need to send a correct _TableName_ value when using _NSLocalizedString method_. Currently AGi18n just sends _tableName = nil_, so that it is only possible to use AGi18n in case all localizable strings are stored in _Localizable.strings_ file.

In order to get this works I would need to override or customize the current AGi18n logic, so it is possible somehow to create relationship between element in _storyboard / xib_ and its _tableName_

Do you have any suggestions? Or maybe you know some other libraries that allow to make it works in such way?

**Comment by stasivanov** [comment]
The one of the way to have "relationship between element in _storyboard / xib_ and its tableName" is to create _@IBInspectable_ properties for each "translationable" element, that AGi18n already have categories for (like UILabel, UITextField, UINavigationItem, etc), so that it will be possible to provide custom tableName right from _Storyboard/XIB_ as _@IBInspectable_ value. 

This would allow to customize the _tableName_ and would not break current logic.

**Comment by stasivanov** [comment]
Let me know, if the flow from my previous comment would work for you. I will then implement that and create a pull request.

**Comment by angelolloqui** [comment]
This works and introduces no backward compatibility issues so it is OK. Merged

**Comment by stasivanov** [comment]
Hi @angelolloqui. Do you know why cocoapods is still showing that the latest version is 0.0.4? "pod search" console command returns 0.0.4, and also search on Cocoapods website also returns 0.0.4. I have tried to update pod repo but that didn't help? 

Is that something happens on Cocoapods side so it has some delay while new version is appear, or there is something wrong with configuration AGi18n pod?

Currently I just link pod straight to the master branch in Podfile, but anyway this looks strange for me so I decided to ask.

Thanks!

**Comment by angelolloqui** [comment]
I am actually trying to push the new version but got some issues. Not sure if it is due to cocoapods or my laptop, but I will try it again.

Thanks for reporting
