### ISSUE TITLE
License text and license name mismatch

### ISSUE THREAD

**Issue by nerminator** [angelolloqui/AGi18n#42]
Hello, the license name in the readme file and the license text in the license file doesn't match. The license name in the Readme file is MIT License. However the license text in the license file seems to be the license text of BSD3-Clause. 

Either the license name in the readme should be updated as 
"BSD 3-Clause 'New' or 'Revised' License" 
or the text in the License file should be updated as in the following link:
https://opensource.org/licenses/MIT

Your license text is same with the following BSD3 text:
https://spdx.org/licenses/BSD-3-Clause.html

We need this update in order to pass our corporate legal checks. Otherwise, we will not be able to use this beautiful library in our app. 

Additionally, we are using a previous version (0.0.2) of the library. You cannot make changes in previous versions in Github. So, in the resolution of this issue could you please add a note like "this resolution also applies for previous versions"?

Thanks for your support.

**Comment by angelolloqui** [comment]
README file updated with BSD3. As stated above, I can not modify old versions, so as suggested I state here that the BSD3 license resolution applies to previous versions as well.
